# Generated by Django 6.0 on 2025-12-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_footercontent_newslettersubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footercontent',
            name='map_embed_url',
        ),
        migrations.RemoveField(
            model_name='footercontent',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='footercontent',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='map_embed',
            field=models.TextField(blank=True, default='', help_text='Paste Google Maps iframe'),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
