# Generated by Django 6.0 on 2025-12-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_footercontent_map_embed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='map_embed',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
