# Generated by Django 6.0 on 2025-12-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_footercontent_updated_at_alter_footercontent_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
        migrations.RemoveField(
            model_name='footercontent',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='map_embed',
            field=models.TextField(help_text='Paste Google Maps iframe code here'),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='whatsapp',
            field=models.CharField(help_text='International format e.g. 233XXXXXXXXX', max_length=20),
        ),
    ]
