# Generated by Django 6.0 on 2025-12-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_newslettersubscriber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='area_of_interest',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
