# Generated by Django 6.0 on 2025-12-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_volunteer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
