# Generated by Django 6.0 on 2025-12-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_article_carouselslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
