# Generated by Django 6.0 on 2025-12-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_carouselslide_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselslide',
            name='layout',
            field=models.CharField(choices=[('center', 'Center'), ('left', 'Left aligned'), ('right', 'Right aligned')], default='center', max_length=10),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='subtitle',
            field=models.TextField(blank=True),
        ),
    ]
