# Generated by Django 6.0 on 2025-12-17 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_carouselslide_layout_alter_carouselslide_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={},
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='order',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='twitter',
        ),
        migrations.AddField(
            model_name='missionvision',
            name='statement_of_faith',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(max_length=150),
        ),
    ]
