# Generated by Django 6.0 on 2025-12-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_teammember_options_remove_teammember_facebook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missionvision',
            old_name='mission',
            new_name='vision_and_purpose',
        ),
        migrations.RemoveField(
            model_name='missionvision',
            name='vision',
        ),
    ]
