# Generated by Django 6.0 on 2025-12-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_teammember_options_remove_teammember_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
