# Generated by Django 6.0 on 2025-12-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_teammember_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoWeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Who We Are', max_length=200)),
                ('content', models.TextField(help_text='Main description for Who We Are section')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Who We Are',
                'verbose_name_plural': 'Who We Are',
            },
        ),
    ]
