# Generated by Django 6.0 on 2025-12-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_whoweare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footercontent',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
