# Generated by Django 6.0 on 2026-01-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_footercontent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='seo_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_title',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]

