# Generated by Django 6.0 on 2026-01-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_blogpost_seo_description_blogpost_seo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Recommend: 150-160 characters', max_length=160),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Recommend: 50-60 characters', max_length=60),
        ),
    ]
