# Generated by Django 6.0 on 2026-01-01 19:43
# Fixed: image field already exists from initial migration; make this a no-op.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_blogpost_seo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
