# Generated by Django 6.0 on 2026-01-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
