# Generated by Django 6.0 on 2026-01-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_project_image_alter_project_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary shown on project listings (auto-generated if empty).'),
        ),
    ]
