# Generated by Django 6.0 on 2026-01-07 18:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_newslettersubscriber_unsubscribed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='unsubscribed_at',
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
