# Generated by Django 6.0 on 2026-01-08 08:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
