# Generated by Django 6.0 on 2026-01-08 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_newslettersubscriber_unsubscribe_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.newslettersubscriber')),
            ],
        ),
    ]
