# Generated by Django 6.0 on 2026-01-09 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_newsletterclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterclick',
            name='newsletter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.newsletter'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NewsletterOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.newsletter')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.newslettersubscriber')),
            ],
            options={
                'unique_together': {('newsletter', 'subscriber')},
            },
        ),
    ]
