# Generated by Django 6.0 on 2026-01-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_newslettersubscriber_unsubscribe_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='body',
            field=models.TextField(help_text='HTML content only (no <html> or <body>)'),
        ),
    ]
