# Generated by Django 6.0 on 2026-01-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_newsletter_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='week_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
