# Generated by Django 6.0 on 2026-01-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_newsletter_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
