# Generated by Django 6.0 on 2026-05-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
