# Generated by Django 6.0 on 2026-05-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_project_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionvision',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Background image for the About Us hero section', null=True, upload_to='about/'),
        ),
    ]
