# Generated by Django 6.0 on 2026-05-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_missionvision_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='week_number',
        ),
    ]
