# Generated by Django 6.0 on 2026-05-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_newsletter_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionvision',
            name='hero_subtitle',
            field=models.CharField(blank=True, default='A community dedicated to shining light in dark places.', help_text='Subtitle shown below the heading', max_length=400),
        ),
        migrations.AddField(
            model_name='missionvision',
            name='hero_title',
            field=models.CharField(default='About Us', help_text='Main heading shown on the About Us hero', max_length=200),
        ),
    ]
