# Generated by Django 6.0 on 2026-05-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_missionvision_hero_subtitle_missionvision_hero_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='excerpt',
        ),
    ]
