# Generated by Django 6.0 on 2026-05-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_directormessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
    ]
