# Generated by Django 6.0 on 2026-08-20

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_remove_blogpost_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                config_name="default",
                verbose_name="Content",
            ),
        ),
    ]