# Generated by Django 6.0.8 on 2026-08-24 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_alter_blogpost_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Transaction ID must contain only ASCII digits.",
                        regex=r"\A[0-9]{1,100}\Z",
                    )
                ],
            ),
        ),
    ]